version: '3'

services:
   db:
     image: trail1_image2
     volumes:
         - /opt/data:/var/lib/mysql
     restart: always
     hostname: db
     environment:
       MYSQL_ROOT_PASSWORD: 2015
       MYSQL_DATABASE: mydb
       MYSQL_USER: root
       
   webapi:
     depends_on:
       - db
     image: trail1_image1
     hostname: webapi
     ports:
       - "8081:8080"
     restart: always